//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStoreIntegrationService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStoreIntegrationService.ServiceResource", typeof(ServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_BLOBNAME.
        /// </summary>
        public static string BlobName {
            get {
                return ResourceManager.GetString("BlobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated translation.
        /// </summary>
        public static string CategoryAutomatedTranslation {
            get {
                return ResourceManager.GetString("CategoryAutomatedTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File filters &amp; converters.
        /// </summary>
        public static string CategoryFileFiltersConverters {
            get {
                return ResourceManager.GetString("CategoryFileFiltersConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminology.
        /// </summary>
        public static string CategoryTerminology {
            get {
                return ResourceManager.GetString("CategoryTerminology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Memory.
        /// </summary>
        public static string CategoryTranslationMemory {
            get {
                return ResourceManager.GetString("CategoryTranslationMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_CONFIGFILENAME.
        /// </summary>
        public static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_LOCAL_FOLDERPATH.
        /// </summary>
        public static string LocalFolderPath {
            get {
                return ResourceManager.GetString("LocalFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_OOS_URI.
        /// </summary>
        public static string OosUri {
            get {
                return ResourceManager.GetString("OosUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid For.
        /// </summary>
        public static string PaidFor {
            get {
                return ResourceManager.GetString("PaidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Description.
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Name.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_STORAGE_ACCOUNTKEY.
        /// </summary>
        public static string StorageAccountKey {
            get {
                return ResourceManager.GetString("StorageAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_STORAGE_ACCOUNTNAME.
        /// </summary>
        public static string StorageAccountName {
            get {
                return ResourceManager.GetString("StorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPINSIGHTS_INSTRUMENTATIONKEY.
        /// </summary>
        public static string TelemetryInstrumentationKey {
            get {
                return ResourceManager.GetString("TelemetryInstrumentationKey", resourceCulture);
            }
        }
    }
}
